baseURL = "https://laserbiolabs.com"
languageCode = "en-us"
title = "LaserBio Labs"
theme = "laserbiolabs"
contentDir = "content"
[params]
    description = "Laserbiolabs website"

[menu]
[[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
[[menu.main]]
    name = 'Products'
    url = '/products'
    weight = '2'
